### ISSUE TITLE
Alcatraz Package Manager

### ISSUE THREAD

**Issue by lfarah** [doubleencore/XcodeIssueGenerator#10]
It would be **awesome** if your plugin was available in [Alcatraz Package Manager](https://github.com/alcatraz/Alcatraz).
It's really easy to do, as you can see [HERE](https://github.com/alcatraz/Alcatraz#i-want-to-submit-my-package):
> Fork the Alcatraz package repository and include your package with name, description, URL, and optional screenshot. Don't forget to submit a pull request. Further instructions are included in the package repository documentation.

**Comment by soolwan** [comment]
Thanks for the suggestion! I think we might want a more Xcode plugin-like version of this tool if we wanted to add it to Alcatraz, right? Something that didn't require making a Run Script build phase and calling an executable?

**Comment by lfarah** [comment]
Definitely!

**Comment by soolwan** [comment]
We've settled on a Homebrew option rather than Alcatraz for now. Instructions are in the README. Thanks!
