### ISSUE TITLE
Easy script

### ISSUE THREAD

**Issue by MaxHasADHD** [doubleencore/XcodeIssueGenerator#12]
I use this script to do show warnings for TODO, WARNING, and FIXME so I don't forget about them.

`KEYWORDS="TODO:|FIXME:|WARNING:|\?\?\?:|\!\!\!:"
find "${SRCROOT}" \( -name "*.swift" \) -print0 | \
xargs -0 egrep --with-filename --line-number --only-matching "($KEYWORDS).*\$" | \
perl -p -e "s/($KEYWORDS)/ warning: \$1/"`

**Comment by soolwan** [comment]
Yes for our purposes we like to generate errors too depending on build configuration, and halt the build if there are errors. And we also need to be able to exclude third-party directories. And it's nice for those features to be configurable as arguments. Thanks!
