### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by mkj-is** [doubleencore/XcodeIssueGenerator#14]
Firstly, let me thank you for the great work you are doing!

I noticed the installation and updates can be little complicated. Have you thought about Homebrew support? I think it would make using the issue generator much easier. And you wouldn't be the only project who would work this way. I am mentioning https://github.com/Flinesoft/BartyCrouch, as an example.

**Comment by soolwan** [comment]
Hi, thanks. We added instructions for Homebrew.
