### ISSUE TITLE
Doesn't find tags with no space after the "//"

### ISSUE THREAD

**Issue by snej** [doubleencore/XcodeIssueGenerator#3]
I use `//TEMP` (with no space) to mark temporary code. (I don't know why there isn't a space. My fingers just type this string automatically, these days.) The regex that looks for tags doesn't find this because it wants exactly one space before the tag.

Could you start the regex with `"//\s*` instead of `"// `, i.e. allow any or no whitespace after the `//`?

**Comment by soolwan** [comment]
Thanks! I have updated the regex in PR #5.
