### ISSUE TITLE
Could not make exclude directory

### ISSUE THREAD

**Issue by idrisr** [doubleencore/XcodeIssueGenerator#6]
I'm getting the message `Could not make exclude directory. Directories should be relative to the project file which is the same as being relative to ($SRCROOT).` when I run the executable from the top level directory of my project directly and in a `Run Script Build Phase`.

My directory structure is as such:

```
MyAppFolder/
    Model/      # source dir
    Controller/ # source dir
    View/       # source dir
    Podfile
    Podfile.lock
    Pods
    README.md
    Services
    Support
    Supporting Files
    MyApp
    MyApp.xcodeproj
    MyApp.xcworkspace
```

The value of `$SRCROOT` is `MyAppFolder`.

Am I breaking some assumptions with the directory structure?

**Comment by soolwan** [comment]
Can you provide the line you have set in your Run Script build phase please? I would expect if you wanted to exclude your View directory you could write ```XcodeIssueGenerator -w "TODO" -b DEBUG -x "View/".

You could try to put an ```echo "$SRCROOT"``` in your Run Script phase and then look in the Report Navigator pane for the build output and take note of what $SRCROOT is for your project. Then base your exclude directories off of that.

**Comment by soolwan** [comment]
Also, usually a new Xcode project has a root folder and then a nested folder of the same name where all of the files exist. In that case you would have to use ```MySampleProject/View/``` as your exclude directory.

**Comment by soolwan** [comment]
I believe this issue is related to not being able to handle $SRCROOT with spaces fixed in #9 and in the latest release v0.5.2. Thanks!

**Comment by idrisr** [comment]
Ok thanks for the response. My needs are simpler than yours right now so I'm going with this: https://bendodson.com/weblog/2014/10/02/showing-todo-as-warning-in-swift-xcode-project/

**Comment by soolwan** [comment]
:thumbsup:
