### ISSUE TITLE
Error with $SRCROOT containing whitespace characters

### ISSUE THREAD

**Issue by christianklotz** [doubleencore/XcodeIssueGenerator#8]
I ran `XCodeIssueGenerator` from the command line with a relative path for `$SRCROOT` set to `./` and it works as expected. However since my project is in a folder that contains a spaces it fails.

    SRCROOT="./" CONFIGURATION=DEBUG XcodeIssueGenerator -b DEBUG -w "WARNING, SERIOUS" -e "TODO" -x "Vendor/"

This gives me the proper output

    ...swift:151: error: // TODO: foo bar
    ...swift:350: error: // TODO: this should be better

#### Example

No matter if relative or absolute, as soon as the path contains spaces it fails.

    SRCROOT="../../My Folder/MyIOSProject" CONFIGURATION=DEBUG XcodeIssueGenerator -b DEBUG -w "WARNING, SERIOUS" -e "TODO" -x "Vendor/"

It also fails with the escaped path instead of using double quotes

    SRCROOT=../../My\ Folder/MyIOSProject CONFIGURATION=DEBUG XcodeIssueGenerator -b DEBUG -w "WARNING, SERIOUS" -e "TODO" -x "Vendor/"

#### Actual Result

    An error ocurred while finding tags.

**Comment by soolwan** [comment]
Thanks for reporting that! I have a fix in PR #9 and in the latest release v0.5.2.
